---
- name: Configuración de Instancia EC2 Worker
  hosts: all
  become: yes
  tasks:
    - name: Instalar cliente svn
      apt:
        name: subversion
        state: present

    - name: Descargar solo la carpeta 'scripts' desde GitHub usando svn
      command: >
        svn checkout https://github.com/campusdualdevopsGrupo2/imatia-rss-engine/trunk/scripts/cloud
        dest=/home/ubuntu/scripts

    - name: Aplicar dos2unix a los archivos .sh copiados
      shell: |
        dos2unix /home/ubuntu/scripts/*.sh

    - name: Generate docker-compose.yml from template
      template:
        src: /home/ubuntu/docker-compose.j2.yml
        dest: /home/ubuntu/docker-compose.yml
        mode: '0644'

    - name: Docker Compose
      command: docker compose up -d 
      args:
        chdir: /home/ubuntu

    - name: Obtener el ID del contenedor Docker
      command: "sudo docker ps --filter 'name=my-worker' -q"
      register: container_id
      changed_when: false
    
    - name: Verificar si se encontró el contenedor
      fail:
        msg: "No se encontró el contenedor 'my-worker'."
      when: container_id.stdout == ""


    - name: Establecer permisos para los scripts en el contenedor
      command: "sudo docker exec {{ container_id.stdout }} chmod +x /app/scripts/{{ item }}"
      loop:
        - job.sh
        - upload.sh
        - process_rss_batch.sh
        - metrics_rss.sh
