services:
  grafana:
    image: grafana/grafana:11.5.2-ubuntu
    container_name: grafana
    restart: unless-stopped
    volumes:
      # - "/mnt/efs/grafana:/var/lib/grafana"
      - "/home/ubuntu/grafana"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
