- name: Configure EC2 Node with Grafana
  hosts: localhost
  connection: local
  become: yes
  tasks:

  - name: Ensure the directory for playbooks exists
    ansible.builtin.file:
      path: /home/ubuntu/playbooks
      state: directory
      mode: '0755'

  - name: Copy Repository (docker-compose.yml)
    ansible.builtin.git:
      src: https://github.com/campusdualdevopsGrupo2/imatia-rss-engine.git
      dest: /home/ubuntu/grafana
      version: "main"
      force: yes

  - name: Copy docker-compose.yml to the correct location
    ansible.builtin.copy:
      src: /home/ubuntu/grafana/ansible/grafana/docker-compose.yml
      dest: /home/ubuntu/grafana/config/docker-compose.yml

  - name: Ensure required directories exist
    ansible.builtin.file:
      path: "/home/ubuntu/grafana/config"
      state: directory
      mode: '0755'
