services:
  myserver:
    image: "flexvega/simple-worker:1.0.0-alpine"  # Imagen del contenedor
    container_name: "myserver"         # Nombre del contenedor
    network_mode: host                 # Usar la red del host
    restart: always                    # Política de reinicio para que siempre se reinicie el contenedor si falla
    ports:
      - "8080:8080"                   # Exponer puertos si es necesario
    deploy:
      resources:
        limits:
          cpus: '1.9'
          memory: 3.8G                # Limitar la RAM
    entrypoint: ["./app-bluengo-worker", "server"]
  
  myserver_add:
    image: "flexvega/simple-worker:1.0.0-alpine"  # Imagen del contenedor
    container_name: "myserver_add"                # Nombre del contenedor (diferente)
    network_mode: host                            # Usar la red del host
    restart: always                               # Política de reinicio                             # Exponer un puerto diferente para evitar conflicto                        # Limitar la RAM
    entrypoint: ["./app-bluengo-worker", "add" , "http://localhosts:8080 "]
  
